[package]
name = "fbx"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
thiserror = "1.0.2"

[dev-dependencies]
clap = { version = "4.0", features = ["derive"] }

[lints]
